### ISSUE TITLE
Fails to install plugin in Logstash 2.1.0 and 2.1.1

### ISSUE THREAD

**Issue by espinraf** [jurmous/logstash-log4j2#15]
From Logstash 2.1.1:
Bundler could not find compatible versions for gem "logstash":
  In Gemfile:
    logstash-input-log4j2 (>= 0) java depends on
      logstash (< 2.0.0, >= 1.4.0) java
Could not find gem 'logstash (< 2.0.0, >= 1.4.0) java', which is required by gem 'logstash-input-log4j2 (>= 0) java', in any of the sources.

**Comment by estanislaobosch** [comment]
A workaround to solve this you can 
0- execute 'gem install logstash-devutils'
1- clone the master branch to path_to_plugin_dir
2- in path_to_plugin_dir execute 'rake vendor'
3- in path_to_plugin_dir execute 'gem build logstash-input-log4j2.gemspec'
4- in path_to_logstash_dir execute './bin/plugin install path_to_plugin_dir/logstash-input-log4j2-5.2-java.gem

Hope this helps

**Comment by espinraf** [comment]
Solved
