### ISSUE TITLE
Logstash doesn't start: port is not opened with log4j2 plugin

### ISSUE THREAD

**Issue by rescolar** [jurmous/logstash-log4j2#6]
Hi!
Thanks for the plugin!
I'm trying to get it work but no luck for the moment.
Logstash-1.4.2 with this is the configuration:

This is my config file:
input {
  log4j2 {
      mode => "server"
      port => 7000
  }
}
output {
  stdout { codec => rubydebug
 }
  elasticsearch { host => localhost }
}

And this is what happens: Logstash doesn't complete the load and doesn't open the port:

Here is how I start it:
/usr/bin/java -Djava.io.tmpdir=/var/lib/logstash -Xmx500m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -Djava.awt.headless=true -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -jar /opt/logstash/vendor/jar/jruby-complete-1.7.11.jar -I/opt/logstash/lib /opt/logstash/lib/logstash/runner.rb agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log --debug --pluginpath /etc/logstash/logstash-log4j2-release-4.0/lib/

The port is not opened:
lsof -nPi:7000

And these are the logstash debug logs:

{:timestamp=>"2015-01-14T10:24:26.386000+0000", :message=>"Adding plugin path", :path=>"/etc/logstash/logstash-log4j2-release-4.0/lib/", :level=>:debug, :file=>"logstash/agent.rb", :line=>"282"}
{:timestamp=>"2015-01-14T10:24:26.403000+0000", :message=>"Reading config file", :file=>"logstash/agent.rb", :level=>:debug, :line=>"301"}
{:timestamp=>"2015-01-14T10:24:26.732000+0000", :message=>"Compiled pipeline code:\n@inputs = []\n@filters = []\n@outputs = []\n@input_log4j2_1 = plugin(\"input\", \"log4j2\", LogStash::Util.hash_merge_many({ \"mode\" => (\"server\".force_encoding(\"UTF-8\")) }, { \"port\" => 7000 }))\n\n@inputs << @input_log4j2_1\n@output_stdout_2 = plugin(\"output\", \"stdout\", LogStash::Util.hash_merge_many({ \"codec\" => (\"rubydebug\".force_encoding(\"UTF-8\")) }))\n\n@outputs << @output_stdout_2\n@output_elasticsearch_3 = plugin(\"output\", \"elasticsearch\", LogStash::Util.hash_merge_many({ \"host\" => (\"localhost\".force_encoding(\"UTF-8\")) }))\n\n@outputs << @output_elasticsearch_3\n  @filter_func = lambda do |event, &block|\n    extra_events = []\n    @logger.debug? && @logger.debug(\"filter received\", :event => event.to_hash)\n    extra_events.each(&block)\n  end\n  @output_func = lambda do |event, &block|\n    @logger.debug? && @logger.debug(\"output received\", :event => event.to_hash)\n    @output_stdout_2.handle(event)\n    @output_elasticsearch_3.handle(event)\n    \n  end", :level=>:debug, :file=>"logstash/pipeline.rb", :line=>"26"}
{:timestamp=>"2015-01-14T10:24:26.963000+0000", :message=>"Using milestone 1 input plugin 'log4j2'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones", :level=>:warn, :file=>"logstash/config/mixin.rb", :line=>"209"}
{:timestamp=>"2015-01-14T10:24:26.991000+0000", :message=>"config LogStash::Codecs::Plain/@charset = \"UTF-8\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:26.997000+0000", :message=>"config LogStash::Inputs::Log4j2/@mode = \"server\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:26.998000+0000", :message=>"config LogStash::Inputs::Log4j2/@port = 7000", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.012000+0000", :message=>"config LogStash::Inputs::Log4j2/@debug = false", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.031000+0000", :message=>"config LogStash::Inputs::Log4j2/@codec = <LogStash::Codecs::Plain charset=>\"UTF-8\">", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.032000+0000", :message=>"config LogStash::Inputs::Log4j2/@add_field = {}", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.033000+0000", :message=>"config LogStash::Inputs::Log4j2/@host = \"0.0.0.0\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.037000+0000", :message=>"config LogStash::Inputs::Log4j2/@data_timeout = 5", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.132000+0000", :message=>"config LogStash::Outputs::Stdout/@codec = <LogStash::Codecs::RubyDebug >", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.134000+0000", :message=>"config LogStash::Outputs::Stdout/@type = \"\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.136000+0000", :message=>"config LogStash::Outputs::Stdout/@tags = []", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.138000+0000", :message=>"config LogStash::Outputs::Stdout/@exclude_tags = []", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.151000+0000", :message=>"config LogStash::Outputs::Stdout/@workers = 1", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.223000+0000", :message=>"config LogStash::Codecs::Plain/@charset = \"UTF-8\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.231000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@host = \"localhost\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.233000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@type = \"\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.247000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@tags = []", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.249000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@exclude_tags = []", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.250000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@codec = <LogStash::Codecs::Plain charset=>\"UTF-8\">", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.256000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@workers = 1", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.257000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@index = \"logstash-%{+YYYY.MM.dd}\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.259000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@manage_template = true", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.260000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@template_name = \"logstash\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.262000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@template_overwrite = false", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.264000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@document_id = nil", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.265000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@embedded = false", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.267000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@embedded_http_port = \"9200-9300\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.272000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@max_inflight_requests = 50", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.274000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@flush_size = 5000", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.283000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@idle_flush_time = 1", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2015-01-14T10:24:27.285000+0000", :message=>"config LogStash::Outputs::ElasticSearch/@action = \"index\"", :level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"105"}

Thanks a lot for your help!
Rafa

**Comment by jurmous** [comment]
Strange, it works for me with logstash 1.4.2. 
Did you try other ports? What is your log4j2.xml config?

Are you using the gem or the separate source download? If you used the source download, did you run "rake vendor" ? (Source does not include the log4j2 jars)

**Comment by rescolar** [comment]
Thanks for the quick answer!
Now I'm pretty sure the problem comes from the plugin installation, since it works for logstash 1.5 with the  automatic installation.
In logstash 1.4 I just unzipped the plugin and then I added --pluginpath /etc/logstash/logstash-log4j2-release-4.0/lib/
to the launch script.  I didn't run any script to build it or to get libraries.
What is the right way to install it on 1.4.2? 
Thanks!

**Comment by jurmous** [comment]
Since the last version of the plugin the jars are not includes in the zip but are downloaded by rake. I see I have not yet included the step to install them in the README. Did you try to install them by running "rake vendor"? (You need to install rake) If you can confirm this was the missing step I will update the README. I could possibly also create a zip which includes them to make it easier.

**Comment by rescolar** [comment]
It would be nice if you explain how to install the plugin from scratch, I mean from a server where you only have logstash installed (I know nothing about ruby devlopment)

I installed rake: yum install rake

But I don't know how to tell rake where my logstash installation is...

> rake vendor
rake aborted!
no such file to load -- logstash/devutils/rake
/etc/logstash/logstash-log4j2-release-4.0/Rakefile:10

Thanks!
R

**Comment by rescolar** [comment]
After copying jar files into $LS_PLUGIN/vendor/ folder it works fine.
log4j-core-2.1.jar
log4j-api-2.1.jar

Thank you for your help.
R

**Comment by jurmous** [comment]
I must be honest and it was also all new for me :) (I am also not a Ruby native and am learning along the way) The rake and gem methods where included by pull request #5 to make the plugin work with logstash 1.5+. 

I have added a zip to the release without all the gem and rake stuff and the jars included for 1.4 versions. This should solve the issue for the less Ruby minded :)
